// SPDX-License-Identifier: MIT
// Copyright (c) 2026 stanbot8
#pragma once
// LOD -1 (coarsest): Spectral ocean surface model.
//
// Gerstner wave superposition with Phillips spectrum sampling for
// deep-water ocean dynamics at km scale. Provides surface height,
// velocity, and pressure at arbitrary world positions without a grid.
//
// Physics:
//   Deep water dispersion: omega^2 = g*k (Airy 1845)
//   Gerstner waves: trochoid surface (peaked crests, flat troughs)
//   Phillips spectrum: P(k) = A * exp(-1/(kL)^2) / k^4
//     where L = V^2/g (Tessendorf 2001)
//   Optional JONSWAP peak enhancement (Hasselmann et al. 1973)
//
// References:
//   Tessendorf, J. (2001) "Simulating Ocean Water" SIGGRAPH Course Notes
//   Phillips, O.M. (1957) "On the generation of waves by turbulent wind"
//     J. Fluid Mech. 2(5), 417-445
//   Hasselmann, K. et al. (1973) "Measurements of wind-wave growth and
//     swell decay during JONSWAP" Dtsch. Hydrogr. Z. A8(12)
//   Kinsman, B. (1965) "Wind Waves" (Prentice-Hall). Orbital velocity.

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <vector>

#include "mjwater/types.h"

namespace mjwater {

// --- Ocean parameters ---

struct OceanParams {
  float wind_speed = 10.0f;       // U_10: wind speed at 10m height (m/s)
  float wind_dir_x = 1.0f;       // wind direction (normalized)
  float wind_dir_y = 0.0f;
  float gravity = kGravity;
  float depth = 1000.0f;          // ocean depth (m); >lambda/2 = deep water
  uint32_t num_waves = 64;        // number of spectral components
  float min_wavelength = 1.0f;    // shortest wavelength to resolve (m)
  float max_wavelength = 300.0f;  // longest wavelength (m); typical ocean swell
  float choppiness = 0.8f;        // Gerstner lateral displacement (0=sinusoidal, 1=full)
  float damping_scale = 0.001f;   // suppresses waves shorter than this * L (m)
  float amplitude_scale = 1.0f;   // overall amplitude multiplier
  float jonswap_gamma = 3.3f;     // JONSWAP peak enhancement (1.0 = Phillips only)
  float jonswap_peak_omega = 0.0f; // peak frequency (rad/s); 0 = auto from wind
};

// --- Single wave component ---

struct OceanWave {
  float kx, ky;       // wave vector components (rad/m)
  float k;            // |k| wavenumber magnitude
  float omega;        // angular frequency (rad/s)
  float amplitude;    // wave amplitude (m)
  float phase;        // initial phase (rad)
};

// --- Spectral ocean solver ---

struct SpectralOceanSolver {
  OceanParams params;
  std::vector<OceanWave> waves;
  float time = 0;

  // Deterministic hash for reproducible phase assignment.
  // Uses integer hashing (no rand() dependency).
  static uint32_t Hash32(uint32_t x) {
    x ^= x >> 16;
    x *= 0x45d9f3bu;
    x ^= x >> 16;
    x *= 0x45d9f3bu;
    x ^= x >> 16;
    return x;
  }

  static float HashToFloat(uint32_t seed) {
    return static_cast<float>(Hash32(seed)) / 4294967295.0f;
  }

  // Phillips spectrum: S(k) = A * exp(-1/(kL)^2) / k^4
  // L = V^2/g (largest wave generated by wind of speed V)
  // A = Phillips constant, typically 3e-3 to 8e-3 (Tessendorf 2001 uses ~4e-3)
  // The constant A is dimensionless in the 1D wavenumber spectrum S(k) [m^3].
  static constexpr float kPhillipsA = 4.0e-3f;

  static float PhillipsSpectrum(float k, float wind_speed, float gravity,
                                 float damping) {
    if (k < 1e-6f) return 0.0f;
    float L = wind_speed * wind_speed / gravity;
    float k2 = k * k;
    float k4 = k2 * k2;
    float phillips = kPhillipsA * std::exp(-1.0f / (k2 * L * L)) / k4;

    // Dampen very short wavelengths (capillary suppression).
    float l2 = damping * damping;
    phillips *= std::exp(-k2 * l2);

    return phillips;
  }

  // JONSWAP peak enhancement factor (Hasselmann et al. 1973).
  // gamma^alpha where alpha = exp(-(omega - omega_p)^2 / (2*sigma^2*omega_p^2))
  // sigma = 0.07 for omega <= omega_p, 0.09 for omega > omega_p
  static float JONSWAPFactor(float omega, float omega_p, float gamma) {
    if (gamma <= 1.0f + 1e-6f) return 1.0f;  // no enhancement
    float sigma = (omega <= omega_p) ? 0.07f : 0.09f;
    float r = (omega - omega_p) / (sigma * omega_p);
    float alpha = std::exp(-0.5f * r * r);
    return std::pow(gamma, alpha);
  }

  // Deep water dispersion relation: omega^2 = g*k*tanh(k*d)
  // For deep water (k*d >> 1): omega = sqrt(g*k)
  float Dispersion(float k) const {
    float kd = k * params.depth;
    if (kd > 10.0f) {
      // Deep water approximation (error < 0.005% for kd > 10).
      return std::sqrt(params.gravity * k);
    }
    // General dispersion with finite depth.
    return std::sqrt(params.gravity * k * std::tanh(kd));
  }

  void Init(const OceanParams& p) {
    params = p;

    // Normalize wind direction.
    float wlen = std::sqrt(p.wind_dir_x * p.wind_dir_x +
                           p.wind_dir_y * p.wind_dir_y);
    float wx = (wlen > 0) ? p.wind_dir_x / wlen : 1.0f;
    float wy = (wlen > 0) ? p.wind_dir_y / wlen : 0.0f;

    // Peak frequency for JONSWAP.
    float omega_p = params.jonswap_peak_omega;
    if (omega_p <= 0) {
      // Pierson-Moskowitz peak: omega_p = 0.877 * g / U_10
      omega_p = 0.877f * params.gravity / std::max(params.wind_speed, 0.1f);
    }

    // Sample wave components across the spectrum.
    float k_min = kTwoPi / params.max_wavelength;
    float k_max = kTwoPi / params.min_wavelength;
    float log_k_min = std::log(k_min);
    float log_k_max = std::log(k_max);

    waves.resize(params.num_waves);
    float L = params.wind_speed * params.wind_speed / params.gravity;

    for (uint32_t i = 0; i < params.num_waves; ++i) {
      // Logarithmic spacing in k for better low-frequency coverage.
      float t = static_cast<float>(i) / std::max(1u, params.num_waves - 1);
      float log_k = log_k_min + t * (log_k_max - log_k_min);
      float k = std::exp(log_k);

      // Directional spread: sample angle within +/- 90 deg of wind.
      // Use cosine-squared directional spreading (Longuet-Higgins 1963).
      float angle_offset = (HashToFloat(i * 7919u + 1u) - 0.5f) * kPi;
      float cos2 = std::cos(angle_offset * 0.5f);
      cos2 *= cos2;  // cos^2 spreading

      float wind_angle = std::atan2(wy, wx);
      float theta = wind_angle + angle_offset;

      float kx = k * std::cos(theta);
      float ky = k * std::sin(theta);

      // Phillips spectrum value.
      float P = PhillipsSpectrum(k, params.wind_speed, params.gravity,
                                  params.damping_scale * L);

      // Directional weighting: Phillips includes cos^2(theta - wind_dir).
      float cos_wind = std::cos(theta - wind_angle);
      float dir_factor = cos_wind * cos_wind;

      // JONSWAP enhancement.
      float omega = Dispersion(k);
      float jonswap = JONSWAPFactor(omega, omega_p, params.jonswap_gamma);

      // Amplitude from spectral density.
      // dk for this bin (logarithmic spacing).
      float dk;
      if (i == 0) {
        dk = std::exp(log_k_min + (log_k_max - log_k_min) /
             std::max(1u, params.num_waves - 1)) - k_min;
      } else if (i == params.num_waves - 1) {
        dk = k_max - std::exp(log_k_max - (log_k_max - log_k_min) /
             std::max(1u, params.num_waves - 1));
      } else {
        float k_prev = std::exp(log_k_min + (t - 1.0f /
                       std::max(1u, params.num_waves - 1)) *
                       (log_k_max - log_k_min));
        float k_next = std::exp(log_k_min + (t + 1.0f /
                       std::max(1u, params.num_waves - 1)) *
                       (log_k_max - log_k_min));
        dk = (k_next - k_prev) * 0.5f;
      }

      float amplitude = std::sqrt(2.0f * P * dir_factor * jonswap *
                                   cos2 * dk) * params.amplitude_scale;

      // Random phase for each wave component (deterministic from index).
      float phase = HashToFloat(i * 104729u + 31u) * kTwoPi;

      waves[i] = {kx, ky, k, omega, amplitude, phase};
    }

    time = 0;
  }

  // Advance time.
  void Step(float dt) { time += dt; }

  // --- Queries at arbitrary world position ---

  // Surface displacement (Gerstner wave superposition).
  // Returns (dx, dy, dz): lateral + vertical displacement.
  Vec3 SurfaceDisplacement(float wx, float wy) const {
    Vec3 d{};
    float Q = params.choppiness;

    for (const auto& w : waves) {
      float theta = w.kx * wx + w.ky * wy - w.omega * time + w.phase;
      float c = std::cos(theta);
      float s = std::sin(theta);

      // Vertical displacement.
      d.z += w.amplitude * c;

      // Gerstner lateral displacement (creates choppy peaks).
      if (w.k > 1e-10f && Q > 0) {
        float factor = Q * w.amplitude / w.k;
        d.x -= w.kx * factor * s;
        d.y -= w.ky * factor * s;
      }
    }
    return d;
  }

  // Surface height at world position (z component of displacement).
  float SurfaceHeight(float wx, float wy) const {
    float z = 0;
    for (const auto& w : waves) {
      float theta = w.kx * wx + w.ky * wy - w.omega * time + w.phase;
      z += w.amplitude * std::cos(theta);
    }
    return z;
  }

  // Orbital velocity at position (x, y, z) where z < 0 is depth.
  // Deep water: u = omega*A*exp(kz)*cos(kx-wt), w = omega*A*exp(kz)*sin(kx-wt)
  // (Kinsman 1965, eq. 3.4.5)
  Vec3 OrbitalVelocity(float wx, float wy, float wz) const {
    Vec3 v{};
    for (const auto& w : waves) {
      float theta = w.kx * wx + w.ky * wy - w.omega * time + w.phase;
      float decay = std::exp(w.k * wz);  // exponential decay with depth (z < 0)
      decay = std::min(decay, 1.0f);      // clamp at surface

      float hor_speed = w.omega * w.amplitude * decay;
      float c = std::cos(theta);
      float s = std::sin(theta);

      // Horizontal velocity in wave propagation direction.
      if (w.k > 1e-10f) {
        v.x += hor_speed * (w.kx / w.k) * c;
        v.y += hor_speed * (w.ky / w.k) * c;
      }
      // Vertical velocity.
      v.z += w.omega * w.amplitude * decay * s;
    }
    return v;
  }

  // Dynamic pressure perturbation at (x, y, z).
  // p' = rho * g * A * exp(kz) * cos(kx - wt) (linear wave theory)
  float DynamicPressure(float wx, float wy, float wz) const {
    float p = 0;
    for (const auto& w : waves) {
      float theta = w.kx * wx + w.ky * wy - w.omega * time + w.phase;
      float decay = std::exp(w.k * wz);
      decay = std::min(decay, 1.0f);
      p += kWaterDensity * params.gravity * w.amplitude * decay *
           std::cos(theta);
    }
    return p;
  }

  // Significant wave height H_s (statistical measure).
  // H_s = 4 * sqrt(m0) where m0 = sum(A_i^2 / 2) is the zeroth spectral moment.
  float SignificantWaveHeight() const {
    float m0 = 0;
    for (const auto& w : waves) m0 += w.amplitude * w.amplitude * 0.5f;
    return 4.0f * std::sqrt(m0);
  }

  // Peak wavelength (longest significant wave).
  float PeakWavelength() const {
    float max_a = 0;
    float peak_k = 1.0f;
    for (const auto& w : waves) {
      if (w.amplitude > max_a) {
        max_a = w.amplitude;
        peak_k = w.k;
      }
    }
    return kTwoPi / peak_k;
  }

  // Total energy per unit area (J/m^2).
  // E = 0.5 * rho * g * sum(A_i^2)
  float TotalEnergy() const {
    float e = 0;
    for (const auto& w : waves) e += w.amplitude * w.amplitude;
    return 0.5f * kWaterDensity * params.gravity * e;
  }
};

}  // namespace mjwater
